# Generated by Django 5.2.8 on 2025-12-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obras', models.ManyToManyField(blank=True, related_name='listas', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'db_table': 'listas',
                'ordering': ['-created_at'],
            },
        ),
    ]
