# Generated by Django 5.2.8 on 2025-11-25 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('url_foto', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL da Foto')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
                'db_table': 'diretores',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('logo', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL do Logo')),
                ('cor', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Cor deve ser #RRGGBB', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor (Hex)')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL do Site')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'plataformas',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('cor', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Cor deve ser #RRGGBB', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor (Hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('sinopse', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sinopse')),
                ('ano_lancamento', models.IntegerField(blank=True, null=True, verbose_name='Ano de Lançamento')),
                ('duracao_minutos', models.IntegerField(blank=True, null=True, verbose_name='Duração (minutos)')),
                ('url_capa', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL da Capa')),
                ('tipo', models.CharField(choices=[('FILME', 'Filme'), ('SERIE', 'Série'), ('DOCUMENTARIO', 'Documentário')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('QUERO_ASSISTIR', 'Quero Assistir'), ('ASSISTINDO', 'Assistindo'), ('ASSISTIDO', 'Assistido')], max_length=20, verbose_name='Status')),
                ('temporada_atual', models.IntegerField(blank=True, null=True)),
                ('episodio_atual', models.IntegerField(blank=True, null=True)),
                ('total_temporadas', models.IntegerField(blank=True, null=True)),
                ('total_episodios', models.IntegerField(blank=True, null=True)),
                ('data_assistido', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diretores', models.ManyToManyField(blank=True, related_name='obras', to='core.diretor')),
                ('generos', models.ManyToManyField(blank=True, related_name='obras', to='core.genero')),
                ('plataformas', models.ManyToManyField(blank=True, related_name='obras', to='core.plataforma')),
                ('tags', models.ManyToManyField(blank=True, related_name='obras', to='core.tag')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(help_text='0.0 a 10.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota')),
                ('comentario', models.CharField(blank=True, max_length=2000, null=True)),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('editado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.obra')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'db_table': 'avaliacoes',
            },
        ),
    ]
