# Generated by Django 5.2.8 on 2025-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Lista')),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(blank=True, choices=[('FAVORITOS', 'Favoritos'), ('ASSISTIDOS', 'Assistidos'), ('QUERO_VER', 'Quero Ver'), ('PERSONALIZADA', 'Personalizada')], max_length=20, null=True, verbose_name='Tipo')),
                ('ordem', models.IntegerField(blank=True, null=True, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obras', models.ManyToManyField(blank=True, related_name='listas', to='core.obra')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'db_table': 'listas',
            },
        ),
    ]
