# Generated by Django 5.2.8 on 2025-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='onde_assistir',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Onde Assistir'),
        ),
    ]
