# Generated by Django 5.2.8 on 2025-11-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obra_onde_assistir'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='comentario',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comentário'),
        ),
    ]
