# Generated by Django 5.2.8 on 2025-12-03 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diretores', '0001_initial'),
        ('generos', '0001_initial'),
        ('plataformas', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('sinopse', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sinopse')),
                ('ano_lancamento', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Lançamento')),
                ('duracao_minutos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração (minutos)')),
                ('url_capa', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL da Capa')),
                ('tipo', models.CharField(choices=[('filme', 'Filme'), ('serie', 'Série')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('quero_assistir', 'Quero Assistir'), ('assistindo', 'Assistindo'), ('assistido', 'Assistido'), ('pausado', 'Pausado'), ('abandonado', 'Abandonado')], max_length=20, verbose_name='Status')),
                ('total_episodios', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Episódios')),
                ('total_temporadas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de Temporadas')),
                ('episodio_atual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Episódio Atual')),
                ('temporada_atual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Temporada Atual')),
                ('comentario', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diretores', models.ManyToManyField(blank=True, related_name='obras', to='diretores.diretor')),
                ('generos', models.ManyToManyField(blank=True, related_name='obras', to='generos.genero')),
                ('plataformas', models.ManyToManyField(blank=True, related_name='obras', to='plataformas.plataforma')),
                ('tags', models.ManyToManyField(blank=True, related_name='obras', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
                'ordering': ['-created_at'],
            },
        ),
    ]
